### PR TITLE
fix(govendor): overwrite stale manifest when clearing dependencies

### LINKED ISSUE #276: govendor skips manifest cleanup when all external dependencies are removed
When a `go.mod` that previously had external dependencies (and thus a generated `govendor.toml`) has all its dependencies removed, running `govendor` reports the module as skipped with `"go.mod has no external dependencies"` and exits without touching the existing stale govendor.toml

### PR DESCRIPTION
**Pull request by Ahhhh-man**
Closes #276

When a `go.mod` that previously had external dependencies (and thus a generated `govendor.toml`) has all its dependencies removed and `go mod tidy` is run, the previous behavior returned `skipped` early and left the stale manifest behind with its outdated dependencies and hash.

Now it when the manifest gets updated with the latest `go.mod` hash with
no dependencies, an empty `[mod]` list is produced.

### CODE REVIEW

File: internal/mod/result.go [hunk 1]
```diff
@@ -89,6 +89,11 @@ func resultMissing(path string) vendorResult {
 	return vendorResult{path: path, status: statusMissing, message: "govendor.toml not found, run govendor to generate"}
 }
 
+func resultStale(path string) vendorResult {
+	ft := fileType(path)
+	return vendorResult{path: path, status: statusDrift, message: fmt.Sprintf("govendor.toml is stale: %s has no external dependencies, run 'govendor' to remove it", ft)}
+}
+
```
Comment (Ahhhh-man) [inline internal/mod/result.go]: This only exists to be verbose but could skip it and just have `resultDrift`.
